full_rebuild: true
name: JSONAPI Suite
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
github:
  url: '/jsonapi_suite'
defaults:
  -
    scope:
      path: ""
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
  entries:
    output: true
    values:
      layout: "index"
  tutorials:
    output: true
    values:
      layout: "index"
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
